### ISSUE TITLE
Missing npm package

### ISSUE THREAD

**Issue by jaridpoe** [danielstern/redux-saga-sandbox#1]
I believe your missing the _babel-cli_ dev dependency. If you clone, install, and start the project there is an error:

<img width="698" alt="screen shot 2017-09-27 at 3 01 30 pm" src="https://user-images.githubusercontent.com/17737116/30934944-c5331f12-a394-11e7-9912-fcd5fafb9756.png">

This is fixed by running _npm install babel-cli -D_

**Comment by danielstern** [comment]
Sounds great! I've updated the package.json to fix this on npm start.
